# Site settings
title: AI Learning Hub
description: Empowering Business Owners with AI Knowledge
baseurl: ""
url: "https://learn.aireinvestor.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - README.md
  - CNAME

# Plugin settings
plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true 