# Site settings
title: AI Learning Hub
description: Empowering Business Owners with AI Knowledge
baseurl: ""
url: "https://learn.aireinvestor.com"

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Defaults
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "announcements"
    values:
      layout: "announcement"

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - .gitignore
  - README.md
  - CNAME

# Plugin settings
plugins:
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

# Navigation Structure
navigation:
  - title: Home
    url: /
  - title: Announcements
    url: /announcements
  - title: Learning Resources
    url: /learn
    subitems:
      - title: AI Patterns & Best Practices
        url: /learn/patterns
      - title: Basic Options & Switches
        url: /learn/basic-options-switches
      - title: Advanced Options Guide
        url: /learn/options
      - title: Linux Cheat Sheet
        url: /learn/linux-cheats
  - title: Join Us
    url: /join-us
  - title: Newsletter
    url: https://freeblog.aireinvestor.com/newsletter
  - title: Podcast
    url: https://freeblog.aireinvestor.com/podcast

# Collections
collections:
  learn:
    output: true
    permalink: /learn/:path/
  announcements:
    output: true
    permalink: /announcements/:title/ 