name: Pages Deployment Monitor

on:
  page_build:
  workflow_dispatch:

jobs:
  deployment-notification:
    runs-on: ubuntu-latest
    steps:
      - name: Check deployment status
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const deployments = await github.rest.repos.listDeployments({
              owner,
              repo,
              environment: 'github-pages'
            });
            
            if (deployments.data.length > 0) {
              const latestDeployment = deployments.data[0];
              const status = await github.rest.repos.listDeploymentStatuses({
                owner,
                repo,
                deployment_id: latestDeployment.id
              });
              
              if (status.data.length > 0) {
                const latestStatus = status.data[0];
                console.log(`Deployment Status: ${latestStatus.state}`);
                console.log(`Environment URL: ${latestStatus.environment_url}`);
                
                if (latestStatus.state === 'success') {
                  console.log('🎉 Site successfully deployed!');
                } else if (latestStatus.state === 'failure') {
                  core.setFailed('Deployment failed');
                }
              }
            }
      
      - name: Create deployment comment
        uses: actions/github-script@v6
        with:
          script: |
            const { owner, repo } = context.repo;
            const commits = await github.rest.repos.listCommits({
              owner,
              repo,
              per_page: 1
            });
            
            if (commits.data.length > 0) {
              const latestCommit = commits.data[0];
              await github.rest.issues.createComment({
                owner,
                repo,
                issue_number: context.issue.number || latestCommit.sha,
                body: `🚀 Site deployment completed!\nView the changes at: https://learn.aireinvestor.com\nDeployment time: ${new Date().toISOString()}`
              });
            } 